import "./globals.css";

import { UserProvider } from '@auth0/nextjs-auth0/client';
import { ChatProvider } from "@/app/[locale]/components/ChatContext";
import { DarkModeProvider } from "@/app/[locale]/components/styledComponents/DarkMode"
import {UserProviderr} from "@/app/[locale]/context/UserContext"
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';

export const metadata = {
  title: "Veranstaltungsplaner",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  // Await `params` before using its properties
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  // Show a custom Status 404 error page if the path is not valid
  //if (!routing.locales.includes(locale)) {
  //  notFound();
  //}

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <DarkModeProvider>
      <body>
        <NextIntlClientProvider messages={messages}>
          <UserProvider>
            <UserProviderr>
              <ChatProvider>
                {children}
              </ChatProvider>
            </UserProviderr>
          </UserProvider>
        </NextIntlClientProvider>
      </body>
      </DarkModeProvider>
    </html>
  );
}
