import "../globals.css";
import SidebarUser from "../components/SidebarUser";
import {Box} from "@mui/material";



export const metadata = {
    title: "Veranstaltungsplaner",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <Box sx={{ display: 'flex', gridTemplateColumns: 'repeat(2, 1fr)' }}>
            <SidebarUser />
            <Box sx={{ p: 2 }}>
                {children}
            </Box>
        </Box>
    );
}
